=== ShipitSmarter/vscode-stitch/schemas/integration.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "Imports": {
      "$ref": "#/definitions/Imports"
    },
    "Request": {
      "$ref": "#/definitions/Request"
    },
    "Steps": {
      "$ref": "#/definitions/Steps"
    },
    "Response": {
      "$ref": "#/definitions/Response"
    }
  },
  "required": [
    "Request",
    "Steps",
    "Response"
  ],
  "definitions": {
    "Imports": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "Request": {
      "type": "object",
      "properties": {
        "AuthenticationMethods": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/AuthenticationMethod"
          }
        }
      },
      "additionalProperties": false,
      "default": [],
      "required": [
        "AuthenticationMethods"
      ]
    },
    "AuthenticationMethod": {
      "type": "object",
      "properties": {
        "Id": {
          "type": "string"
        },
        "Key": {
          "type": "string"
        },
        "Description": {
          "type": "string"
        }
      },
      "required": [
        "Id",
        "Key",
        "Description"
      ],
      "additionalProperties": false
    },
    "Steps": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "anyOf": [
          {
            "$ref": "#/definitions/HttpStep"
          },
          {
            "$ref": "#/definitions/SftpStep"
          }
        ]
      },
      "minItems": 1
    },
    "HttpStep": {
      "type": "object",
      "default": {
        "$type": "Core.Entities.Configs.Steps.HttpConfiguration, Core",
        "Id": "",
        "Template": "",
        "Method": "POST",
        "Url": ""
      },
      "description": "Make a web-request",
      "properties": {
        "$type": {
          "enum": [
            "Core.Entities.Configs.Steps.HttpConfiguration, Core"
          ]
        },
        "Id": {
          "type": "string"
        },
        "Template": {
          "type": "string"
        },
        "SuccessCondition": {
          "type": "string"
        },
        "StartCondition": {
          "type": "string"
        },
        "Method": {
          "enum": [
            "GET",
            "POST",
            "PUT",
            "DELETE",
            "PATCH",
            "HEAD",
            "OPTIONS",
            "TRACE"
          ]
        },
        "Headers": {
          "$ref": "#/definitions/Headers"
        },
        "Url": {
          "type": "string"
        }
      },
      "required": [
        "$type",
        "Id",
        "Template",
        "Method",
        "Url"
      ]
    },
    "SftpStep": {
      "type": "object",
      "default": {
        "$type": "Core.Entities.Configs.Steps.SftpConfiguration, Core",
        "Id": "",
        "Template": "",
        "Host": "",
        "Port": 21,
        "Username": "",
        "Password": "",
        "Filename": ""
      },
      "description": "Put file on FTP location",
      "properties": {
        "$type": {
          "enum": [
            "Core.Entities.Configs.Steps.SftpConfiguration, Core"
          ]
        },
        "Id": {
          "type": "string"
        },
        "Template": {
          "type": "string"
        },
        "SuccessCondition": {
          "type": "string"
        },
        "StartCondition": {
          "type": "string"
        },
        "Host": {
          "type": "string"
        },
        "Port": {
          "type": "number"
        },
        "Username": {
          "type": "string"
        },
        "Password": {
          "type": "string"
        },
        "Path": {
          "type": "string"
        },
        "Filename": {
          "type": "string"
        }
      },
      "required": [
        "$type",
        "Id",
        "Template",
        "Host",
        "Port",
        "Username",
        "Password",
        "Filename"
      ]
    },
    "Response": {
      "type": "object",
      "properties": {
        "Body": {
          "type": "string"
        },
        "Headers": {
          "$ref": "#/definitions/Headers"
        },
        "StatusCode": {
          "type": "number"
        }
      },
      "required": [
        "Body"
      ],
      "additionalProperties": false
    },
    "Headers": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    }
  }
}

=== ShipitSmarter/vscode-stitch/demo/simple/sftp/handle.integration.json
{
    "Imports": [],
    "Request": {
        "AuthenticationMethods": [
            {
                "Key": "hash-1-h9T0FpQspCjYGuYOTlgvUcwTXxizb2IsNB2Wt5RD5hnNu/qG",
                "Id": "DummyStitch",
                "Description": "DummyStitch"
            }
        ]
    },
    "Steps": [
        {
            "$type": "Core.Entities.Configs.Steps.SftpConfiguration, Core",
            "Id": "SftpUpload",
            "Host": "{{ Model.host }}",
            "Port":  21,
            "Filename": "{{ Model.filename }}",
            "Template": "{{ include 'file.sbn' }}",
            "Path": "{{ Model.path }}",
            "Username": "{{ Model.username }}",
            "Password": "@Microsoft.Keyvault(SecretName=test)"
        }
    ],
    "Response": {
        "StatusCode": 200,
        "Body": "{}"
    }
}

=== ShipitSmarter/vscode-stitch/demo/simple/raw-http/query/automation.integration.json
{
    "Request": {
        "AuthenticationMethods": [
            {
                "Key": "hash-1-asd/asd",
                "Id": "dummy-ConnectKeyId",
                "Description": "dummy"
            }
        ]
    },
    "Steps": [
        {
            "$type": "Core.Entities.Configs.Steps.HttpConfiguration, Core",
            "Id": "FirstOne",
            "Headers": {
                "Content-Type": "application/json"
            },
            "Method": "POST",
            "Url": "https://example.com",
            "Template": ""
        }
    ],
    "Imports": [],
    "Response": {
        "Body": "{{ include 'response-body.sbn' }}",
        "Headers": {},
        "StatusCode": 200
    }
}

=== ShipitSmarter/vscode-stitch/demo/noScenario/noScenario.integration.json
{
    "Imports": [],
    "Request": {
        "AuthenticationMethods": [
            {
                "Key": "hash-1-asd/asd",
                "Id": "dummy-ConnectKeyId",
                "Description": "dummy"
            }
        ]
    },
    "Steps": [
        {
            "$type": "Core.Entities.Configs.Steps.HttpConfiguration, Core",
            "Id": "TrackingXML",
            "Headers": {
                "Content-Type": "application/x-www-form-urlencoded"
            },
            "Method": "POST",
            "Url": "https://express.tnt.com/expressconnect/track.do",
            "Template": "{{ include 'request-body.json' }}"
        }
    ],
    "Response": {
        "Body": "{{ include 'response-body.json' }}",
        "Headers": {},
        "StatusCode": 200
    }
}

=== ShipitSmarter/vscode-stitch/demo/simple/http/automation.integration.json
{
    "Request": {
        "AuthenticationMethods": [
            {
                "Key": "hash-1-asd/asd",
                "Id": "dummy-ConnectKeyId",
                "Description": "dummy"
            }
        ]
    },
    "Steps": [
        {
            "$type": "Core.Entities.Configs.Steps.HttpConfiguration, Core",
            "Id": "TrackingXML",
            "Headers": {
                "Content-Type": "application/x-www-form-urlencoded"
            },
            "Method": "POST",
            "Url": "https://express.tnt.com/expressconnect/track.do",
            "Template": "{{ include 'request-body.sbn' }}"
        }
    ],
    "Imports": [],
    "Response": {
        "Body": "{{ include 'response-body.sbn' }}",
        "Headers": {},
        "StatusCode": 200
    }
}

=== ShipitSmarter/vscode-stitch/demo/withImports/track/read.integration.json
{
    "Imports": [
        "../imports/codecompany-{{Model.Shipment.CodeCompany}}.json",
        "../imports/{{Environment}}.json"
    ],
    "Request": {
        "AuthenticationMethods": [
            {
                "Id":"sis",
                "Key": "{{Imports.SisApiKey}}",
                "Description": "This is the main key that is send from carrier config in catch"
            }
        ]
    },
    "Steps": [
        {
            "$type": "Core.Entities.Configs.Steps.HttpConfiguration, Core",
            "Id": "Track",
            "Method": "GET",
            "Headers":{},
            "Url": "https://api-gw.dhlparcel.nl/track-trace?key={{Model.Shipment.AWB}}",
            "Template": ""
        }
    ],
    "Response": {
        "Body": "{{include 'response-body.json'}}",
        "Headers": {},
        "StatusCode": 200
    }
}
